### ISSUE TITLE
TypeError: serviceWorker.register() must be called with a script URL whose protocol is either HTTP or HTTP

### ISSUE THREAD

**Issue by qwerty084** [washanhanzi/tauri-qwik-tailwind-starter#2]
Hey, do you know how to fix: TypeError: serviceWorker.register() must be called with a script URL whose protocol is either HTTP or HTTP

After building the tauri app for production i get this error and the service worker cannot be registered.

**Comment by washanhanzi** [comment]
No, haven't seen that before. I saw tauri update the doc for [qwik](https://tauri.app/v1/guides/getting-started/setup/qwik). Maybe you can share more info or you can try with that guide. I also update the repo for qwik 1.1.4.

**Comment by qwerty084** [comment]
Im having the same error in a new project following the tauri documentation. I think its not possible to register a service worker in tauri without the localhost plugin. Anyways its not an error in the template.
